/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.clevertec;

import org.apache.commons.lang3.math.NumberUtils;

public class StringUtils {
    public boolean isPositiveNumber(String string) {
        if (!NumberUtils.isCreatable(string)) {
            throw new NumberFormatException(string + " couldn't convert to number");
        }
        Double num = NumberUtils.createDouble(string);
        return num > 0;
    }
}
